# Generated by Django 4.2.9 on 2024-06-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='descuento_bodega',
            field=models.FloatField(blank=True, null=True, verbose_name='Descuento Bodega'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='descuento_depto',
            field=models.FloatField(blank=True, null=True, verbose_name='Descuento Depto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='descuento_estacionamiento',
            field=models.FloatField(blank=True, null=True, verbose_name='Descuento Estacionamiento'),
        ),
    ]
