# Generated by Django 4.2.9 on 2024-06-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_cotizacion_descuento_bodega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a')], default='Soltero/a', max_length=30, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Promesa', 'En Promesa')], default='Pendiente', max_length=20, verbose_name='Estado Reserva'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_promesa_ven',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Promsa Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_ven',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('Contado', 'Contado'), ('Crédito', 'Crédito')], default='Crédito', max_length=30, verbose_name='Forma Pago'),
        ),
    ]
