# Generated by Django 4.2.9 on 2024-06-14 20:41

import Proyectos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bienes_Extra',
            fields=[
                ('id_bien_extra', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bien', models.CharField(max_length=100, verbose_name='Nombre')),
                ('valor_bien', models.FloatField(validators=[Proyectos.models.validar_positivo], verbose_name='Valor')),
                ('rol_bien', models.CharField(max_length=100, verbose_name='Rol')),
                ('descuento_maximo', models.FloatField(validators=[Proyectos.models.validar_descuento], verbose_name='Descuento')),
                ('estado_bien', models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible')], default='Disponible', max_length=30, verbose_name='Estado')),
            ],
            options={
                'db_table': 'bienes_extras',
            },
        ),
    ]
