# Generated by Django 4.2.9 on 2024-06-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comisione',
            fields=[
                ('id_comision', models.AutoField(primary_key=True, serialize=False)),
                ('id_venta', models.CharField(max_length=10, verbose_name='Id Venta')),
                ('id_asesor', models.CharField(max_length=10, verbose_name='Id Asesor')),
                ('id_cliente', models.CharField(max_length=10, verbose_name='Id Cliente')),
                ('fecha_registro', models.DateField(verbose_name='Fecha Registro')),
                ('fecha_promesa', models.DateField(verbose_name='Fecha Promesa')),
                ('fecha_escritura', models.DateField(blank=True, verbose_name='Fecha Escritura')),
                ('fecha_desistimiento', models.DateField(blank=True, verbose_name='Fecha Desistimiento')),
                ('valor_uf', models.FloatField(verbose_name='Valor UF')),
                ('concepto', models.CharField(max_length=10, verbose_name='Concepto del Registro')),
                ('proyecto', models.CharField(max_length=10, verbose_name='Proyecto asociado')),
                ('etapa', models.CharField(max_length=10, verbose_name='Etapa asociada')),
                ('unidad', models.CharField(max_length=10, verbose_name='Unidad vendida')),
                ('bono_precio', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Aplica Bono Precio')),
                ('monto_venta', models.FloatField(max_length=10, verbose_name='Monto Final Venta')),
                ('porcentaje_comision', models.FloatField(verbose_name='Porcentaje Comisión')),
                ('comision_uf', models.FloatField(verbose_name='Monto Comisión UF')),
                ('comision_promesa_uf', models.FloatField(verbose_name='Monto Comisión x promesa en UF')),
                ('comision_promesa_clp', models.FloatField(verbose_name='Monto Comisión x promesa en CLP')),
                ('comision_escritura_uf', models.FloatField(blank=True, verbose_name='Monto Comisión x escritura en UF')),
                ('comision_escritura_clp', models.FloatField(blank=True, verbose_name='Monto Comisión x escritura en CLP')),
                ('bono_precio_uf', models.FloatField(blank=True, verbose_name='Monto Bono Precio en UF')),
                ('bono_precio_promesa_uf', models.FloatField(blank=True, verbose_name='Monto Bono Precio Promesa en UF')),
                ('bono_precio_promesa_clp', models.FloatField(blank=True, verbose_name='Monto Bono Precio Promesa en CLP')),
                ('bono_precio_escritura_uf', models.FloatField(blank=True, verbose_name='Monto Bono Precio esctitura en UF')),
                ('bono_precio_escritura_clp', models.FloatField(blank=True, verbose_name='Monto Bono Precio Escritura en CLP')),
                ('monto_bono_c1', models.FloatField(blank=True, verbose_name='Monto Bono C1')),
                ('monto_bono_c2', models.FloatField(blank=True, verbose_name='Monto Bono C2')),
                ('monto_bono_c3', models.FloatField(blank=True, verbose_name='Monto Bono C3')),
                ('monto_desistimiento', models.FloatField(blank=True, verbose_name='Monto Desistimiento')),
                ('total_comisiones', models.FloatField(verbose_name='Total Comisiones')),
                ('saldo_pagar', models.FloatField(verbose_name='Saldo a pagar del Total Comisiones')),
                ('total_bonos', models.FloatField(verbose_name='Total Bonos')),
                ('total_bonos_comisiones', models.FloatField(verbose_name='Total Bonos + Comisiones')),
            ],
            options={
                'db_table': 'comisiones',
            },
        ),
        migrations.CreateModel(
            name='Parametros_Comisione',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.DateField(verbose_name='Perido de parametros')),
                ('id_asesor', models.CharField(max_length=10, verbose_name='Asesor')),
                ('meta_venta', models.IntegerField(verbose_name='Meta de venta')),
                ('venta_real', models.IntegerField(verbose_name='Venta real del periodo')),
                ('renta_base', models.IntegerField(verbose_name='Renta base del periodo')),
                ('porcentaje_comision', models.FloatField(verbose_name='Porcentaje comisión')),
                ('prorcentaje_bono_precio', models.FloatField(verbose_name='Porcentaje Bono precio')),
            ],
            options={
                'db_table': 'parametros_comisiones',
            },
        ),
    ]
